# Generated by Django 5.2.3 on 2025-06-11 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del ejercicio', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha del entrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.PositiveIntegerField(help_text='Número de repeticiones completadas')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso levantado (en kg o lb)', max_digits=5)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ejercicio')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='tracker.sesionentrenamiento')),
            ],
        ),
    ]
