# Generated by Django 5.2.3 on 2025-06-25 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(help_text='Ej: Lunes, Martes...', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='registroset',
            name='tiempo_descanso',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de descanso en segundos', null=True),
        ),
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroset',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registroset',
            name='repeticiones',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sesionentrenamiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='EjercicioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.CharField(max_length=20)),
                ('peso_recomendado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dia_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='tracker.diaplan')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diaplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='tracker.plansemanal'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso corporal en kg', max_digits=5)),
                ('objetivos', models.TextField(help_text='Metas de fitness del usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
