# Generated by Django 5.2.3 on 2025-06-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_diaplan_registroset_tiempo_descanso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura en cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad en años', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nivel_fitness',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', help_text='Nivel de fitness actual', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='objetivos',
            field=models.TextField(blank=True, help_text='Metas de fitness del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso corporal en kg', max_digits=5, null=True),
        ),
    ]
