# Generated by Django 5.2.3 on 2025-06-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userprofile_altura_userprofile_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del ejercicio', null=True),
        ),
    ]
