# Generated by Django 5.2.3 on 2025-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_ejercicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='muscle_group',
            field=models.CharField(blank=True, help_text='Grupo muscular principal', max_length=50, null=True),
        ),
    ]
